using InvoiceProcessing.Core.Model;

namespace InvoiceProcessing.Tests;

internal static class TestData
{
    /// <summary>testdata/ in the repository (generated by tools/TestInvoiceGenerator).</summary>
    public static string Folder { get; } = FindFolder();

    public static string File(string prefix) =>
        Directory.GetFiles(Folder).Single(f => Path.GetFileName(f).StartsWith(prefix, StringComparison.Ordinal));

    public static Invoice Invoice(params InvoiceLine[] lines)
    {
        var net = lines.Sum(l => l.NetAmount);
        var tax = Math.Round(net * 0.19m, 2, MidpointRounding.AwayFromZero);
        return new Invoice
        {
            InvoiceNumber = "RE-1",
            InvoiceDate = new DateOnly(2026, 9, 28),
            Currency = "EUR",
            Supplier = new Party("Lieferant GmbH", "DE811234567", null, null, null),
            NetTotal = net,
            TaxTotal = tax,
            GrossTotal = net + tax,
            Lines = lines,
        };
    }

    public static InvoiceLine Line(decimal quantity, decimal price, decimal net, decimal? discountPercent = null, decimal vat = 19, int number = 1) => new()
    {
        LineNumber = number,
        Description = "Artikel",
        Quantity = quantity,
        UnitPrice = price,
        DiscountPercent = discountPercent,
        NetAmount = net,
        VatRate = vat,
    };

    private static string FindFolder()
    {
        for (var directory = new DirectoryInfo(AppContext.BaseDirectory); directory is not null; directory = directory.Parent)
        {
            var candidate = Path.Combine(directory.FullName, "testdata");
            if (Directory.Exists(candidate)) return candidate;
        }

        throw new DirectoryNotFoundException("testdata/ not found – run tools/TestInvoiceGenerator first.");
    }
}
